window.esdocSearchIndex = [
  [
    "@doc.ai/exposomics/apps/airquality/client/components/heatmap/index.js~heatmap",
    "class/apps/airQuality/client/components/Heatmap/index.js~Heatmap.html",
    "<span>Heatmap</span> <span class=\"search-result-import-path\">@doc.ai/exposomics/apps/airQuality/client/components/Heatmap/index.js</span>",
    "class"
  ],
  [
    "@doc.ai/exposomics/apps/precipitation/client/components/heatmap/index.js~heatmap",
    "class/apps/precipitation/client/components/Heatmap/index.js~Heatmap.html",
    "<span>Heatmap</span> <span class=\"search-result-import-path\">@doc.ai/exposomics/apps/precipitation/client/components/Heatmap/index.js</span>",
    "class"
  ],
  [
    "@doc.ai/exposomics/apps/snow/client/components/heatmap/index.js~heatmap",
    "class/apps/snow/client/components/Heatmap/index.js~Heatmap.html",
    "<span>Heatmap</span> <span class=\"search-result-import-path\">@doc.ai/exposomics/apps/snow/client/components/Heatmap/index.js</span>",
    "class"
  ],
  [
    "@doc.ai/exposomics/apps/temphigh/client/components/heatmap/index.js~heatmap",
    "class/apps/tempHigh/client/components/Heatmap/index.js~Heatmap.html",
    "<span>Heatmap</span> <span class=\"search-result-import-path\">@doc.ai/exposomics/apps/tempHigh/client/components/Heatmap/index.js</span>",
    "class"
  ],
  [
    "@doc.ai/exposomics/apps/templow/client/components/heatmap/index.js~heatmap",
    "class/apps/tempLow/client/components/Heatmap/index.js~Heatmap.html",
    "<span>Heatmap</span> <span class=\"search-result-import-path\">@doc.ai/exposomics/apps/tempLow/client/components/Heatmap/index.js</span>",
    "class"
  ],
  [
    "@doc.ai/exposomics/apps/airquality/client/components/heatmap/heatmaprow.js~heatmaprow",
    "class/apps/airQuality/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html",
    "<span>HeatmapRow</span> <span class=\"search-result-import-path\">@doc.ai/exposomics/apps/airQuality/client/components/Heatmap/HeatmapRow.js</span>",
    "class"
  ],
  [
    "@doc.ai/exposomics/apps/precipitation/client/components/heatmap/heatmaprow.js~heatmaprow",
    "class/apps/precipitation/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html",
    "<span>HeatmapRow</span> <span class=\"search-result-import-path\">@doc.ai/exposomics/apps/precipitation/client/components/Heatmap/HeatmapRow.js</span>",
    "class"
  ],
  [
    "@doc.ai/exposomics/apps/snow/client/components/heatmap/heatmaprow.js~heatmaprow",
    "class/apps/snow/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html",
    "<span>HeatmapRow</span> <span class=\"search-result-import-path\">@doc.ai/exposomics/apps/snow/client/components/Heatmap/HeatmapRow.js</span>",
    "class"
  ],
  [
    "@doc.ai/exposomics/apps/temphigh/client/components/heatmap/heatmaprow.js~heatmaprow",
    "class/apps/tempHigh/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html",
    "<span>HeatmapRow</span> <span class=\"search-result-import-path\">@doc.ai/exposomics/apps/tempHigh/client/components/Heatmap/HeatmapRow.js</span>",
    "class"
  ],
  [
    "@doc.ai/exposomics/apps/templow/client/components/heatmap/heatmaprow.js~heatmaprow",
    "class/apps/tempLow/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html",
    "<span>HeatmapRow</span> <span class=\"search-result-import-path\">@doc.ai/exposomics/apps/tempLow/client/components/Heatmap/HeatmapRow.js</span>",
    "class"
  ],
  [
    "@doc.ai/exposomics/apps/airquality/client/view.js~view",
    "class/apps/airQuality/client/View.js~View.html",
    "<span>View</span> <span class=\"search-result-import-path\">@doc.ai/exposomics/apps/airQuality/client/View.js</span>",
    "class"
  ],
  [
    "@doc.ai/exposomics/apps/precipitation/client/view.js~view",
    "class/apps/precipitation/client/View.js~View.html",
    "<span>View</span> <span class=\"search-result-import-path\">@doc.ai/exposomics/apps/precipitation/client/View.js</span>",
    "class"
  ],
  [
    "@doc.ai/exposomics/apps/snow/client/view.js~view",
    "class/apps/snow/client/View.js~View.html",
    "<span>View</span> <span class=\"search-result-import-path\">@doc.ai/exposomics/apps/snow/client/View.js</span>",
    "class"
  ],
  [
    "@doc.ai/exposomics/apps/temphigh/client/view.js~view",
    "class/apps/tempHigh/client/View.js~View.html",
    "<span>View</span> <span class=\"search-result-import-path\">@doc.ai/exposomics/apps/tempHigh/client/View.js</span>",
    "class"
  ],
  [
    "@doc.ai/exposomics/apps/templow/client/view.js~view",
    "class/apps/tempLow/client/View.js~View.html",
    "<span>View</span> <span class=\"search-result-import-path\">@doc.ai/exposomics/apps/tempLow/client/View.js</span>",
    "class"
  ],
  [
    "@doc.ai/exposomics/apps/airquality/server/index.js~controller",
    "function/index.html#static-function-controller",
    "<span>controller</span> <span class=\"search-result-import-path\">@doc.ai/exposomics/apps/airQuality/server/index.js</span>",
    "function"
  ],
  [
    "@doc.ai/exposomics/apps/precipitation/server/index.js~controller",
    "function/index.html#static-function-controller",
    "<span>controller</span> <span class=\"search-result-import-path\">@doc.ai/exposomics/apps/precipitation/server/index.js</span>",
    "function"
  ],
  [
    "@doc.ai/exposomics/apps/snow/server/index.js~controller",
    "function/index.html#static-function-controller",
    "<span>controller</span> <span class=\"search-result-import-path\">@doc.ai/exposomics/apps/snow/server/index.js</span>",
    "function"
  ],
  [
    "@doc.ai/exposomics/apps/temphigh/server/index.js~controller",
    "function/index.html#static-function-controller",
    "<span>controller</span> <span class=\"search-result-import-path\">@doc.ai/exposomics/apps/tempHigh/server/index.js</span>",
    "function"
  ],
  [
    "@doc.ai/exposomics/apps/templow/server/index.js~controller",
    "function/index.html#static-function-controller",
    "<span>controller</span> <span class=\"search-result-import-path\">@doc.ai/exposomics/apps/tempLow/server/index.js</span>",
    "function"
  ],
  [
    "@doc.ai/exposomics/apps/airquality/client/components/heatmap/getrelativecoordinates.js~getrelativecoordinates",
    "function/index.html#static-function-getRelativeCoordinates",
    "<span>getRelativeCoordinates</span> <span class=\"search-result-import-path\">@doc.ai/exposomics/apps/airQuality/client/components/Heatmap/getRelativeCoordinates.js</span>",
    "function"
  ],
  [
    "@doc.ai/exposomics/apps/precipitation/client/components/heatmap/getrelativecoordinates.js~getrelativecoordinates",
    "function/index.html#static-function-getRelativeCoordinates",
    "<span>getRelativeCoordinates</span> <span class=\"search-result-import-path\">@doc.ai/exposomics/apps/precipitation/client/components/Heatmap/getRelativeCoordinates.js</span>",
    "function"
  ],
  [
    "@doc.ai/exposomics/apps/snow/client/components/heatmap/getrelativecoordinates.js~getrelativecoordinates",
    "function/index.html#static-function-getRelativeCoordinates",
    "<span>getRelativeCoordinates</span> <span class=\"search-result-import-path\">@doc.ai/exposomics/apps/snow/client/components/Heatmap/getRelativeCoordinates.js</span>",
    "function"
  ],
  [
    "@doc.ai/exposomics/apps/temphigh/client/components/heatmap/getrelativecoordinates.js~getrelativecoordinates",
    "function/index.html#static-function-getRelativeCoordinates",
    "<span>getRelativeCoordinates</span> <span class=\"search-result-import-path\">@doc.ai/exposomics/apps/tempHigh/client/components/Heatmap/getRelativeCoordinates.js</span>",
    "function"
  ],
  [
    "@doc.ai/exposomics/apps/templow/client/components/heatmap/getrelativecoordinates.js~getrelativecoordinates",
    "function/index.html#static-function-getRelativeCoordinates",
    "<span>getRelativeCoordinates</span> <span class=\"search-result-import-path\">@doc.ai/exposomics/apps/tempLow/client/components/Heatmap/getRelativeCoordinates.js</span>",
    "function"
  ],
  [
    "@doc.ai/exposomics/apps/airquality/server/preparedata.js~preparedata",
    "function/index.html#static-function-prepareData",
    "<span>prepareData</span> <span class=\"search-result-import-path\">@doc.ai/exposomics/apps/airQuality/server/prepareData.js</span>",
    "function"
  ],
  [
    "@doc.ai/exposomics/apps/precipitation/server/preparedata.js~preparedata",
    "function/index.html#static-function-prepareData",
    "<span>prepareData</span> <span class=\"search-result-import-path\">@doc.ai/exposomics/apps/precipitation/server/prepareData.js</span>",
    "function"
  ],
  [
    "@doc.ai/exposomics/apps/snow/server/preparedata.js~preparedata",
    "function/index.html#static-function-prepareData",
    "<span>prepareData</span> <span class=\"search-result-import-path\">@doc.ai/exposomics/apps/snow/server/prepareData.js</span>",
    "function"
  ],
  [
    "@doc.ai/exposomics/apps/temphigh/server/preparedata.js~preparedata",
    "function/index.html#static-function-prepareData",
    "<span>prepareData</span> <span class=\"search-result-import-path\">@doc.ai/exposomics/apps/tempHigh/server/prepareData.js</span>",
    "function"
  ],
  [
    "@doc.ai/exposomics/apps/templow/server/preparedata.js~preparedata",
    "function/index.html#static-function-prepareData",
    "<span>prepareData</span> <span class=\"search-result-import-path\">@doc.ai/exposomics/apps/tempLow/server/prepareData.js</span>",
    "function"
  ],
  [
    "apps/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "apps/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "apps/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "apps/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "apps/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "apps/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "apps/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "apps/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "apps/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "apps/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "apps/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "apps/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "apps/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "apps/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "apps/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "apps/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "apps/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "apps/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "apps/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "apps/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "apps/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "apps/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "apps/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "apps/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "apps/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "apps/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "apps/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "apps/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "apps/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "apps/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "apps/.external-ecmascript.js~String",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "apps/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "apps/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "apps/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "apps/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "apps/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "apps/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "apps/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "apps/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "apps/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "apps/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "apps/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "apps/.external-ecmascript.js~function",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "apps/.external-ecmascript.js~null",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "apps/.external-ecmascript.js~number",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "apps/.external-ecmascript.js~object",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "apps/.external-ecmascript.js~string",
    "external"
  ],
  [
    "apps/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "apps/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "apps/airquality/client/view.js",
    "file/apps/airQuality/client/View.js.html",
    "apps/airQuality/client/View.js",
    "file"
  ],
  [
    "apps/airquality/client/view.js~view#render",
    "class/apps/airQuality/client/View.js~View.html#instance-method-render",
    "apps/airQuality/client/View.js~View#render",
    "method"
  ],
  [
    "apps/airquality/client/view.js~view.proptypes",
    "class/apps/airQuality/client/View.js~View.html#static-member-propTypes",
    "apps/airQuality/client/View.js~View.propTypes",
    "member"
  ],
  [
    "apps/airquality/client/components/heatmap/heatmaprow.js",
    "file/apps/airQuality/client/components/Heatmap/HeatmapRow.js.html",
    "apps/airQuality/client/components/Heatmap/HeatmapRow.js",
    "file"
  ],
  [
    "apps/airquality/client/components/heatmap/heatmaprow.js~heatmaprow#componentdidmount",
    "class/apps/airQuality/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html#instance-method-componentDidMount",
    "apps/airQuality/client/components/Heatmap/HeatmapRow.js~HeatmapRow#componentDidMount",
    "method"
  ],
  [
    "apps/airquality/client/components/heatmap/heatmaprow.js~heatmaprow#componentdidupdate",
    "class/apps/airQuality/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html#instance-method-componentDidUpdate",
    "apps/airQuality/client/components/Heatmap/HeatmapRow.js~HeatmapRow#componentDidUpdate",
    "method"
  ],
  [
    "apps/airquality/client/components/heatmap/heatmaprow.js~heatmaprow#drawcanvas",
    "class/apps/airQuality/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html#instance-method-drawCanvas",
    "apps/airQuality/client/components/Heatmap/HeatmapRow.js~HeatmapRow#drawCanvas",
    "method"
  ],
  [
    "apps/airquality/client/components/heatmap/heatmaprow.js~heatmaprow#handlemove",
    "class/apps/airQuality/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html#instance-member-handleMove",
    "apps/airQuality/client/components/Heatmap/HeatmapRow.js~HeatmapRow#handleMove",
    "member"
  ],
  [
    "apps/airquality/client/components/heatmap/heatmaprow.js~heatmaprow#node",
    "class/apps/airQuality/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html#instance-member-node",
    "apps/airQuality/client/components/Heatmap/HeatmapRow.js~HeatmapRow#node",
    "member"
  ],
  [
    "apps/airquality/client/components/heatmap/heatmaprow.js~heatmaprow#render",
    "class/apps/airQuality/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html#instance-method-render",
    "apps/airQuality/client/components/Heatmap/HeatmapRow.js~HeatmapRow#render",
    "method"
  ],
  [
    "apps/airquality/client/components/heatmap/heatmaprow.js~heatmaprow.defaultprops",
    "class/apps/airQuality/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html#static-member-defaultProps",
    "apps/airQuality/client/components/Heatmap/HeatmapRow.js~HeatmapRow.defaultProps",
    "member"
  ],
  [
    "apps/airquality/client/components/heatmap/heatmaprow.js~heatmaprow.proptypes",
    "class/apps/airQuality/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html#static-member-propTypes",
    "apps/airQuality/client/components/Heatmap/HeatmapRow.js~HeatmapRow.propTypes",
    "member"
  ],
  [
    "apps/airquality/client/components/heatmap/getrelativecoordinates.js",
    "file/apps/airQuality/client/components/Heatmap/getRelativeCoordinates.js.html",
    "apps/airQuality/client/components/Heatmap/getRelativeCoordinates.js",
    "file"
  ],
  [
    "apps/airquality/client/components/heatmap/index.js",
    "file/apps/airQuality/client/components/Heatmap/index.js.html",
    "apps/airQuality/client/components/Heatmap/index.js",
    "file"
  ],
  [
    "apps/airquality/client/components/heatmap/index.js~heatmap#clearcoords",
    "class/apps/airQuality/client/components/Heatmap/index.js~Heatmap.html#instance-member-clearCoords",
    "apps/airQuality/client/components/Heatmap/index.js~Heatmap#clearCoords",
    "member"
  ],
  [
    "apps/airquality/client/components/heatmap/index.js~heatmap#componentwillreceiveprops",
    "class/apps/airQuality/client/components/Heatmap/index.js~Heatmap.html#instance-method-componentWillReceiveProps",
    "apps/airQuality/client/components/Heatmap/index.js~Heatmap#componentWillReceiveProps",
    "method"
  ],
  [
    "apps/airquality/client/components/heatmap/index.js~heatmap#constructor",
    "class/apps/airQuality/client/components/Heatmap/index.js~Heatmap.html#instance-constructor-constructor",
    "apps/airQuality/client/components/Heatmap/index.js~Heatmap#constructor",
    "method"
  ],
  [
    "apps/airquality/client/components/heatmap/index.js~heatmap#container",
    "class/apps/airQuality/client/components/Heatmap/index.js~Heatmap.html#instance-member-container",
    "apps/airQuality/client/components/Heatmap/index.js~Heatmap#container",
    "member"
  ],
  [
    "apps/airquality/client/components/heatmap/index.js~heatmap#handlemousemove",
    "class/apps/airQuality/client/components/Heatmap/index.js~Heatmap.html#instance-member-handleMouseMove",
    "apps/airQuality/client/components/Heatmap/index.js~Heatmap#handleMouseMove",
    "member"
  ],
  [
    "apps/airquality/client/components/heatmap/index.js~heatmap#render",
    "class/apps/airQuality/client/components/Heatmap/index.js~Heatmap.html#instance-method-render",
    "apps/airQuality/client/components/Heatmap/index.js~Heatmap#render",
    "method"
  ],
  [
    "apps/airquality/client/components/heatmap/index.js~heatmap#selectentry",
    "class/apps/airQuality/client/components/Heatmap/index.js~Heatmap.html#instance-member-selectEntry",
    "apps/airQuality/client/components/Heatmap/index.js~Heatmap#selectEntry",
    "member"
  ],
  [
    "apps/airquality/client/components/heatmap/index.js~heatmap#state",
    "class/apps/airQuality/client/components/Heatmap/index.js~Heatmap.html#instance-member-state",
    "apps/airQuality/client/components/Heatmap/index.js~Heatmap#state",
    "member"
  ],
  [
    "apps/airquality/client/components/heatmap/index.js~heatmap.defaultprops",
    "class/apps/airQuality/client/components/Heatmap/index.js~Heatmap.html#static-member-defaultProps",
    "apps/airQuality/client/components/Heatmap/index.js~Heatmap.defaultProps",
    "member"
  ],
  [
    "apps/airquality/client/components/heatmap/index.js~heatmap.proptypes",
    "class/apps/airQuality/client/components/Heatmap/index.js~Heatmap.html#static-member-propTypes",
    "apps/airQuality/client/components/Heatmap/index.js~Heatmap.propTypes",
    "member"
  ],
  [
    "apps/airquality/client/index.js",
    "file/apps/airQuality/client/index.js.html",
    "apps/airQuality/client/index.js",
    "file"
  ],
  [
    "apps/airquality/server/index.js",
    "file/apps/airQuality/server/index.js.html",
    "apps/airQuality/server/index.js",
    "file"
  ],
  [
    "apps/airquality/server/models/airqualityrecord.js",
    "file/apps/airQuality/server/models/AirQualityRecord.js.html",
    "apps/airQuality/server/models/AirQualityRecord.js",
    "file"
  ],
  [
    "apps/airquality/server/preparedata.js",
    "file/apps/airQuality/server/prepareData.js.html",
    "apps/airQuality/server/prepareData.js",
    "file"
  ],
  [
    "apps/index.client.js",
    "file/apps/index.client.js.html",
    "apps/index.client.js",
    "file"
  ],
  [
    "apps/index.server.js",
    "file/apps/index.server.js.html",
    "apps/index.server.js",
    "file"
  ],
  [
    "apps/precipitation/client/view.js",
    "file/apps/precipitation/client/View.js.html",
    "apps/precipitation/client/View.js",
    "file"
  ],
  [
    "apps/precipitation/client/view.js~view#render",
    "class/apps/precipitation/client/View.js~View.html#instance-method-render",
    "apps/precipitation/client/View.js~View#render",
    "method"
  ],
  [
    "apps/precipitation/client/view.js~view.proptypes",
    "class/apps/precipitation/client/View.js~View.html#static-member-propTypes",
    "apps/precipitation/client/View.js~View.propTypes",
    "member"
  ],
  [
    "apps/precipitation/client/components/heatmap/heatmaprow.js",
    "file/apps/precipitation/client/components/Heatmap/HeatmapRow.js.html",
    "apps/precipitation/client/components/Heatmap/HeatmapRow.js",
    "file"
  ],
  [
    "apps/precipitation/client/components/heatmap/heatmaprow.js~heatmaprow#componentdidmount",
    "class/apps/precipitation/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html#instance-method-componentDidMount",
    "apps/precipitation/client/components/Heatmap/HeatmapRow.js~HeatmapRow#componentDidMount",
    "method"
  ],
  [
    "apps/precipitation/client/components/heatmap/heatmaprow.js~heatmaprow#componentdidupdate",
    "class/apps/precipitation/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html#instance-method-componentDidUpdate",
    "apps/precipitation/client/components/Heatmap/HeatmapRow.js~HeatmapRow#componentDidUpdate",
    "method"
  ],
  [
    "apps/precipitation/client/components/heatmap/heatmaprow.js~heatmaprow#drawcanvas",
    "class/apps/precipitation/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html#instance-method-drawCanvas",
    "apps/precipitation/client/components/Heatmap/HeatmapRow.js~HeatmapRow#drawCanvas",
    "method"
  ],
  [
    "apps/precipitation/client/components/heatmap/heatmaprow.js~heatmaprow#handlemove",
    "class/apps/precipitation/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html#instance-member-handleMove",
    "apps/precipitation/client/components/Heatmap/HeatmapRow.js~HeatmapRow#handleMove",
    "member"
  ],
  [
    "apps/precipitation/client/components/heatmap/heatmaprow.js~heatmaprow#node",
    "class/apps/precipitation/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html#instance-member-node",
    "apps/precipitation/client/components/Heatmap/HeatmapRow.js~HeatmapRow#node",
    "member"
  ],
  [
    "apps/precipitation/client/components/heatmap/heatmaprow.js~heatmaprow#render",
    "class/apps/precipitation/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html#instance-method-render",
    "apps/precipitation/client/components/Heatmap/HeatmapRow.js~HeatmapRow#render",
    "method"
  ],
  [
    "apps/precipitation/client/components/heatmap/heatmaprow.js~heatmaprow.defaultprops",
    "class/apps/precipitation/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html#static-member-defaultProps",
    "apps/precipitation/client/components/Heatmap/HeatmapRow.js~HeatmapRow.defaultProps",
    "member"
  ],
  [
    "apps/precipitation/client/components/heatmap/heatmaprow.js~heatmaprow.proptypes",
    "class/apps/precipitation/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html#static-member-propTypes",
    "apps/precipitation/client/components/Heatmap/HeatmapRow.js~HeatmapRow.propTypes",
    "member"
  ],
  [
    "apps/precipitation/client/components/heatmap/getrelativecoordinates.js",
    "file/apps/precipitation/client/components/Heatmap/getRelativeCoordinates.js.html",
    "apps/precipitation/client/components/Heatmap/getRelativeCoordinates.js",
    "file"
  ],
  [
    "apps/precipitation/client/components/heatmap/index.js",
    "file/apps/precipitation/client/components/Heatmap/index.js.html",
    "apps/precipitation/client/components/Heatmap/index.js",
    "file"
  ],
  [
    "apps/precipitation/client/components/heatmap/index.js~heatmap#clearcoords",
    "class/apps/precipitation/client/components/Heatmap/index.js~Heatmap.html#instance-member-clearCoords",
    "apps/precipitation/client/components/Heatmap/index.js~Heatmap#clearCoords",
    "member"
  ],
  [
    "apps/precipitation/client/components/heatmap/index.js~heatmap#componentwillreceiveprops",
    "class/apps/precipitation/client/components/Heatmap/index.js~Heatmap.html#instance-method-componentWillReceiveProps",
    "apps/precipitation/client/components/Heatmap/index.js~Heatmap#componentWillReceiveProps",
    "method"
  ],
  [
    "apps/precipitation/client/components/heatmap/index.js~heatmap#constructor",
    "class/apps/precipitation/client/components/Heatmap/index.js~Heatmap.html#instance-constructor-constructor",
    "apps/precipitation/client/components/Heatmap/index.js~Heatmap#constructor",
    "method"
  ],
  [
    "apps/precipitation/client/components/heatmap/index.js~heatmap#container",
    "class/apps/precipitation/client/components/Heatmap/index.js~Heatmap.html#instance-member-container",
    "apps/precipitation/client/components/Heatmap/index.js~Heatmap#container",
    "member"
  ],
  [
    "apps/precipitation/client/components/heatmap/index.js~heatmap#handlemousemove",
    "class/apps/precipitation/client/components/Heatmap/index.js~Heatmap.html#instance-member-handleMouseMove",
    "apps/precipitation/client/components/Heatmap/index.js~Heatmap#handleMouseMove",
    "member"
  ],
  [
    "apps/precipitation/client/components/heatmap/index.js~heatmap#render",
    "class/apps/precipitation/client/components/Heatmap/index.js~Heatmap.html#instance-method-render",
    "apps/precipitation/client/components/Heatmap/index.js~Heatmap#render",
    "method"
  ],
  [
    "apps/precipitation/client/components/heatmap/index.js~heatmap#selectentry",
    "class/apps/precipitation/client/components/Heatmap/index.js~Heatmap.html#instance-member-selectEntry",
    "apps/precipitation/client/components/Heatmap/index.js~Heatmap#selectEntry",
    "member"
  ],
  [
    "apps/precipitation/client/components/heatmap/index.js~heatmap#state",
    "class/apps/precipitation/client/components/Heatmap/index.js~Heatmap.html#instance-member-state",
    "apps/precipitation/client/components/Heatmap/index.js~Heatmap#state",
    "member"
  ],
  [
    "apps/precipitation/client/components/heatmap/index.js~heatmap.defaultprops",
    "class/apps/precipitation/client/components/Heatmap/index.js~Heatmap.html#static-member-defaultProps",
    "apps/precipitation/client/components/Heatmap/index.js~Heatmap.defaultProps",
    "member"
  ],
  [
    "apps/precipitation/client/components/heatmap/index.js~heatmap.proptypes",
    "class/apps/precipitation/client/components/Heatmap/index.js~Heatmap.html#static-member-propTypes",
    "apps/precipitation/client/components/Heatmap/index.js~Heatmap.propTypes",
    "member"
  ],
  [
    "apps/precipitation/client/index.js",
    "file/apps/precipitation/client/index.js.html",
    "apps/precipitation/client/index.js",
    "file"
  ],
  [
    "apps/precipitation/server/index.js",
    "file/apps/precipitation/server/index.js.html",
    "apps/precipitation/server/index.js",
    "file"
  ],
  [
    "apps/precipitation/server/models/temperaturerecord.js",
    "file/apps/precipitation/server/models/TemperatureRecord.js.html",
    "apps/precipitation/server/models/TemperatureRecord.js",
    "file"
  ],
  [
    "apps/precipitation/server/preparedata.js",
    "file/apps/precipitation/server/prepareData.js.html",
    "apps/precipitation/server/prepareData.js",
    "file"
  ],
  [
    "apps/snow/client/view.js",
    "file/apps/snow/client/View.js.html",
    "apps/snow/client/View.js",
    "file"
  ],
  [
    "apps/snow/client/view.js~view#render",
    "class/apps/snow/client/View.js~View.html#instance-method-render",
    "apps/snow/client/View.js~View#render",
    "method"
  ],
  [
    "apps/snow/client/view.js~view.proptypes",
    "class/apps/snow/client/View.js~View.html#static-member-propTypes",
    "apps/snow/client/View.js~View.propTypes",
    "member"
  ],
  [
    "apps/snow/client/components/heatmap/heatmaprow.js",
    "file/apps/snow/client/components/Heatmap/HeatmapRow.js.html",
    "apps/snow/client/components/Heatmap/HeatmapRow.js",
    "file"
  ],
  [
    "apps/snow/client/components/heatmap/heatmaprow.js~heatmaprow#componentdidmount",
    "class/apps/snow/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html#instance-method-componentDidMount",
    "apps/snow/client/components/Heatmap/HeatmapRow.js~HeatmapRow#componentDidMount",
    "method"
  ],
  [
    "apps/snow/client/components/heatmap/heatmaprow.js~heatmaprow#componentdidupdate",
    "class/apps/snow/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html#instance-method-componentDidUpdate",
    "apps/snow/client/components/Heatmap/HeatmapRow.js~HeatmapRow#componentDidUpdate",
    "method"
  ],
  [
    "apps/snow/client/components/heatmap/heatmaprow.js~heatmaprow#drawcanvas",
    "class/apps/snow/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html#instance-method-drawCanvas",
    "apps/snow/client/components/Heatmap/HeatmapRow.js~HeatmapRow#drawCanvas",
    "method"
  ],
  [
    "apps/snow/client/components/heatmap/heatmaprow.js~heatmaprow#handlemove",
    "class/apps/snow/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html#instance-member-handleMove",
    "apps/snow/client/components/Heatmap/HeatmapRow.js~HeatmapRow#handleMove",
    "member"
  ],
  [
    "apps/snow/client/components/heatmap/heatmaprow.js~heatmaprow#node",
    "class/apps/snow/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html#instance-member-node",
    "apps/snow/client/components/Heatmap/HeatmapRow.js~HeatmapRow#node",
    "member"
  ],
  [
    "apps/snow/client/components/heatmap/heatmaprow.js~heatmaprow#render",
    "class/apps/snow/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html#instance-method-render",
    "apps/snow/client/components/Heatmap/HeatmapRow.js~HeatmapRow#render",
    "method"
  ],
  [
    "apps/snow/client/components/heatmap/heatmaprow.js~heatmaprow.defaultprops",
    "class/apps/snow/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html#static-member-defaultProps",
    "apps/snow/client/components/Heatmap/HeatmapRow.js~HeatmapRow.defaultProps",
    "member"
  ],
  [
    "apps/snow/client/components/heatmap/heatmaprow.js~heatmaprow.proptypes",
    "class/apps/snow/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html#static-member-propTypes",
    "apps/snow/client/components/Heatmap/HeatmapRow.js~HeatmapRow.propTypes",
    "member"
  ],
  [
    "apps/snow/client/components/heatmap/getrelativecoordinates.js",
    "file/apps/snow/client/components/Heatmap/getRelativeCoordinates.js.html",
    "apps/snow/client/components/Heatmap/getRelativeCoordinates.js",
    "file"
  ],
  [
    "apps/snow/client/components/heatmap/index.js",
    "file/apps/snow/client/components/Heatmap/index.js.html",
    "apps/snow/client/components/Heatmap/index.js",
    "file"
  ],
  [
    "apps/snow/client/components/heatmap/index.js~heatmap#clearcoords",
    "class/apps/snow/client/components/Heatmap/index.js~Heatmap.html#instance-member-clearCoords",
    "apps/snow/client/components/Heatmap/index.js~Heatmap#clearCoords",
    "member"
  ],
  [
    "apps/snow/client/components/heatmap/index.js~heatmap#componentwillreceiveprops",
    "class/apps/snow/client/components/Heatmap/index.js~Heatmap.html#instance-method-componentWillReceiveProps",
    "apps/snow/client/components/Heatmap/index.js~Heatmap#componentWillReceiveProps",
    "method"
  ],
  [
    "apps/snow/client/components/heatmap/index.js~heatmap#constructor",
    "class/apps/snow/client/components/Heatmap/index.js~Heatmap.html#instance-constructor-constructor",
    "apps/snow/client/components/Heatmap/index.js~Heatmap#constructor",
    "method"
  ],
  [
    "apps/snow/client/components/heatmap/index.js~heatmap#container",
    "class/apps/snow/client/components/Heatmap/index.js~Heatmap.html#instance-member-container",
    "apps/snow/client/components/Heatmap/index.js~Heatmap#container",
    "member"
  ],
  [
    "apps/snow/client/components/heatmap/index.js~heatmap#handlemousemove",
    "class/apps/snow/client/components/Heatmap/index.js~Heatmap.html#instance-member-handleMouseMove",
    "apps/snow/client/components/Heatmap/index.js~Heatmap#handleMouseMove",
    "member"
  ],
  [
    "apps/snow/client/components/heatmap/index.js~heatmap#render",
    "class/apps/snow/client/components/Heatmap/index.js~Heatmap.html#instance-method-render",
    "apps/snow/client/components/Heatmap/index.js~Heatmap#render",
    "method"
  ],
  [
    "apps/snow/client/components/heatmap/index.js~heatmap#selectentry",
    "class/apps/snow/client/components/Heatmap/index.js~Heatmap.html#instance-member-selectEntry",
    "apps/snow/client/components/Heatmap/index.js~Heatmap#selectEntry",
    "member"
  ],
  [
    "apps/snow/client/components/heatmap/index.js~heatmap#state",
    "class/apps/snow/client/components/Heatmap/index.js~Heatmap.html#instance-member-state",
    "apps/snow/client/components/Heatmap/index.js~Heatmap#state",
    "member"
  ],
  [
    "apps/snow/client/components/heatmap/index.js~heatmap.defaultprops",
    "class/apps/snow/client/components/Heatmap/index.js~Heatmap.html#static-member-defaultProps",
    "apps/snow/client/components/Heatmap/index.js~Heatmap.defaultProps",
    "member"
  ],
  [
    "apps/snow/client/components/heatmap/index.js~heatmap.proptypes",
    "class/apps/snow/client/components/Heatmap/index.js~Heatmap.html#static-member-propTypes",
    "apps/snow/client/components/Heatmap/index.js~Heatmap.propTypes",
    "member"
  ],
  [
    "apps/snow/client/index.js",
    "file/apps/snow/client/index.js.html",
    "apps/snow/client/index.js",
    "file"
  ],
  [
    "apps/snow/server/index.js",
    "file/apps/snow/server/index.js.html",
    "apps/snow/server/index.js",
    "file"
  ],
  [
    "apps/snow/server/models/temperaturerecord.js",
    "file/apps/snow/server/models/TemperatureRecord.js.html",
    "apps/snow/server/models/TemperatureRecord.js",
    "file"
  ],
  [
    "apps/snow/server/preparedata.js",
    "file/apps/snow/server/prepareData.js.html",
    "apps/snow/server/prepareData.js",
    "file"
  ],
  [
    "apps/temphigh/client/view.js",
    "file/apps/tempHigh/client/View.js.html",
    "apps/tempHigh/client/View.js",
    "file"
  ],
  [
    "apps/temphigh/client/view.js~view#render",
    "class/apps/tempHigh/client/View.js~View.html#instance-method-render",
    "apps/tempHigh/client/View.js~View#render",
    "method"
  ],
  [
    "apps/temphigh/client/view.js~view.proptypes",
    "class/apps/tempHigh/client/View.js~View.html#static-member-propTypes",
    "apps/tempHigh/client/View.js~View.propTypes",
    "member"
  ],
  [
    "apps/temphigh/client/components/heatmap/heatmaprow.js",
    "file/apps/tempHigh/client/components/Heatmap/HeatmapRow.js.html",
    "apps/tempHigh/client/components/Heatmap/HeatmapRow.js",
    "file"
  ],
  [
    "apps/temphigh/client/components/heatmap/heatmaprow.js~heatmaprow#componentdidmount",
    "class/apps/tempHigh/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html#instance-method-componentDidMount",
    "apps/tempHigh/client/components/Heatmap/HeatmapRow.js~HeatmapRow#componentDidMount",
    "method"
  ],
  [
    "apps/temphigh/client/components/heatmap/heatmaprow.js~heatmaprow#componentdidupdate",
    "class/apps/tempHigh/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html#instance-method-componentDidUpdate",
    "apps/tempHigh/client/components/Heatmap/HeatmapRow.js~HeatmapRow#componentDidUpdate",
    "method"
  ],
  [
    "apps/temphigh/client/components/heatmap/heatmaprow.js~heatmaprow#drawcanvas",
    "class/apps/tempHigh/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html#instance-method-drawCanvas",
    "apps/tempHigh/client/components/Heatmap/HeatmapRow.js~HeatmapRow#drawCanvas",
    "method"
  ],
  [
    "apps/temphigh/client/components/heatmap/heatmaprow.js~heatmaprow#handlemove",
    "class/apps/tempHigh/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html#instance-member-handleMove",
    "apps/tempHigh/client/components/Heatmap/HeatmapRow.js~HeatmapRow#handleMove",
    "member"
  ],
  [
    "apps/temphigh/client/components/heatmap/heatmaprow.js~heatmaprow#node",
    "class/apps/tempHigh/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html#instance-member-node",
    "apps/tempHigh/client/components/Heatmap/HeatmapRow.js~HeatmapRow#node",
    "member"
  ],
  [
    "apps/temphigh/client/components/heatmap/heatmaprow.js~heatmaprow#render",
    "class/apps/tempHigh/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html#instance-method-render",
    "apps/tempHigh/client/components/Heatmap/HeatmapRow.js~HeatmapRow#render",
    "method"
  ],
  [
    "apps/temphigh/client/components/heatmap/heatmaprow.js~heatmaprow.defaultprops",
    "class/apps/tempHigh/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html#static-member-defaultProps",
    "apps/tempHigh/client/components/Heatmap/HeatmapRow.js~HeatmapRow.defaultProps",
    "member"
  ],
  [
    "apps/temphigh/client/components/heatmap/heatmaprow.js~heatmaprow.proptypes",
    "class/apps/tempHigh/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html#static-member-propTypes",
    "apps/tempHigh/client/components/Heatmap/HeatmapRow.js~HeatmapRow.propTypes",
    "member"
  ],
  [
    "apps/temphigh/client/components/heatmap/getrelativecoordinates.js",
    "file/apps/tempHigh/client/components/Heatmap/getRelativeCoordinates.js.html",
    "apps/tempHigh/client/components/Heatmap/getRelativeCoordinates.js",
    "file"
  ],
  [
    "apps/temphigh/client/components/heatmap/index.js",
    "file/apps/tempHigh/client/components/Heatmap/index.js.html",
    "apps/tempHigh/client/components/Heatmap/index.js",
    "file"
  ],
  [
    "apps/temphigh/client/components/heatmap/index.js~heatmap#clearcoords",
    "class/apps/tempHigh/client/components/Heatmap/index.js~Heatmap.html#instance-member-clearCoords",
    "apps/tempHigh/client/components/Heatmap/index.js~Heatmap#clearCoords",
    "member"
  ],
  [
    "apps/temphigh/client/components/heatmap/index.js~heatmap#componentwillreceiveprops",
    "class/apps/tempHigh/client/components/Heatmap/index.js~Heatmap.html#instance-method-componentWillReceiveProps",
    "apps/tempHigh/client/components/Heatmap/index.js~Heatmap#componentWillReceiveProps",
    "method"
  ],
  [
    "apps/temphigh/client/components/heatmap/index.js~heatmap#constructor",
    "class/apps/tempHigh/client/components/Heatmap/index.js~Heatmap.html#instance-constructor-constructor",
    "apps/tempHigh/client/components/Heatmap/index.js~Heatmap#constructor",
    "method"
  ],
  [
    "apps/temphigh/client/components/heatmap/index.js~heatmap#container",
    "class/apps/tempHigh/client/components/Heatmap/index.js~Heatmap.html#instance-member-container",
    "apps/tempHigh/client/components/Heatmap/index.js~Heatmap#container",
    "member"
  ],
  [
    "apps/temphigh/client/components/heatmap/index.js~heatmap#handlemousemove",
    "class/apps/tempHigh/client/components/Heatmap/index.js~Heatmap.html#instance-member-handleMouseMove",
    "apps/tempHigh/client/components/Heatmap/index.js~Heatmap#handleMouseMove",
    "member"
  ],
  [
    "apps/temphigh/client/components/heatmap/index.js~heatmap#render",
    "class/apps/tempHigh/client/components/Heatmap/index.js~Heatmap.html#instance-method-render",
    "apps/tempHigh/client/components/Heatmap/index.js~Heatmap#render",
    "method"
  ],
  [
    "apps/temphigh/client/components/heatmap/index.js~heatmap#selectentry",
    "class/apps/tempHigh/client/components/Heatmap/index.js~Heatmap.html#instance-member-selectEntry",
    "apps/tempHigh/client/components/Heatmap/index.js~Heatmap#selectEntry",
    "member"
  ],
  [
    "apps/temphigh/client/components/heatmap/index.js~heatmap#state",
    "class/apps/tempHigh/client/components/Heatmap/index.js~Heatmap.html#instance-member-state",
    "apps/tempHigh/client/components/Heatmap/index.js~Heatmap#state",
    "member"
  ],
  [
    "apps/temphigh/client/components/heatmap/index.js~heatmap.defaultprops",
    "class/apps/tempHigh/client/components/Heatmap/index.js~Heatmap.html#static-member-defaultProps",
    "apps/tempHigh/client/components/Heatmap/index.js~Heatmap.defaultProps",
    "member"
  ],
  [
    "apps/temphigh/client/components/heatmap/index.js~heatmap.proptypes",
    "class/apps/tempHigh/client/components/Heatmap/index.js~Heatmap.html#static-member-propTypes",
    "apps/tempHigh/client/components/Heatmap/index.js~Heatmap.propTypes",
    "member"
  ],
  [
    "apps/temphigh/client/index.js",
    "file/apps/tempHigh/client/index.js.html",
    "apps/tempHigh/client/index.js",
    "file"
  ],
  [
    "apps/temphigh/server/index.js",
    "file/apps/tempHigh/server/index.js.html",
    "apps/tempHigh/server/index.js",
    "file"
  ],
  [
    "apps/temphigh/server/models/temperaturerecord.js",
    "file/apps/tempHigh/server/models/TemperatureRecord.js.html",
    "apps/tempHigh/server/models/TemperatureRecord.js",
    "file"
  ],
  [
    "apps/temphigh/server/preparedata.js",
    "file/apps/tempHigh/server/prepareData.js.html",
    "apps/tempHigh/server/prepareData.js",
    "file"
  ],
  [
    "apps/templow/client/view.js",
    "file/apps/tempLow/client/View.js.html",
    "apps/tempLow/client/View.js",
    "file"
  ],
  [
    "apps/templow/client/view.js~view#render",
    "class/apps/tempLow/client/View.js~View.html#instance-method-render",
    "apps/tempLow/client/View.js~View#render",
    "method"
  ],
  [
    "apps/templow/client/view.js~view.proptypes",
    "class/apps/tempLow/client/View.js~View.html#static-member-propTypes",
    "apps/tempLow/client/View.js~View.propTypes",
    "member"
  ],
  [
    "apps/templow/client/components/heatmap/heatmaprow.js",
    "file/apps/tempLow/client/components/Heatmap/HeatmapRow.js.html",
    "apps/tempLow/client/components/Heatmap/HeatmapRow.js",
    "file"
  ],
  [
    "apps/templow/client/components/heatmap/heatmaprow.js~heatmaprow#componentdidmount",
    "class/apps/tempLow/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html#instance-method-componentDidMount",
    "apps/tempLow/client/components/Heatmap/HeatmapRow.js~HeatmapRow#componentDidMount",
    "method"
  ],
  [
    "apps/templow/client/components/heatmap/heatmaprow.js~heatmaprow#componentdidupdate",
    "class/apps/tempLow/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html#instance-method-componentDidUpdate",
    "apps/tempLow/client/components/Heatmap/HeatmapRow.js~HeatmapRow#componentDidUpdate",
    "method"
  ],
  [
    "apps/templow/client/components/heatmap/heatmaprow.js~heatmaprow#drawcanvas",
    "class/apps/tempLow/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html#instance-method-drawCanvas",
    "apps/tempLow/client/components/Heatmap/HeatmapRow.js~HeatmapRow#drawCanvas",
    "method"
  ],
  [
    "apps/templow/client/components/heatmap/heatmaprow.js~heatmaprow#handlemove",
    "class/apps/tempLow/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html#instance-member-handleMove",
    "apps/tempLow/client/components/Heatmap/HeatmapRow.js~HeatmapRow#handleMove",
    "member"
  ],
  [
    "apps/templow/client/components/heatmap/heatmaprow.js~heatmaprow#node",
    "class/apps/tempLow/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html#instance-member-node",
    "apps/tempLow/client/components/Heatmap/HeatmapRow.js~HeatmapRow#node",
    "member"
  ],
  [
    "apps/templow/client/components/heatmap/heatmaprow.js~heatmaprow#render",
    "class/apps/tempLow/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html#instance-method-render",
    "apps/tempLow/client/components/Heatmap/HeatmapRow.js~HeatmapRow#render",
    "method"
  ],
  [
    "apps/templow/client/components/heatmap/heatmaprow.js~heatmaprow.defaultprops",
    "class/apps/tempLow/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html#static-member-defaultProps",
    "apps/tempLow/client/components/Heatmap/HeatmapRow.js~HeatmapRow.defaultProps",
    "member"
  ],
  [
    "apps/templow/client/components/heatmap/heatmaprow.js~heatmaprow.proptypes",
    "class/apps/tempLow/client/components/Heatmap/HeatmapRow.js~HeatmapRow.html#static-member-propTypes",
    "apps/tempLow/client/components/Heatmap/HeatmapRow.js~HeatmapRow.propTypes",
    "member"
  ],
  [
    "apps/templow/client/components/heatmap/getrelativecoordinates.js",
    "file/apps/tempLow/client/components/Heatmap/getRelativeCoordinates.js.html",
    "apps/tempLow/client/components/Heatmap/getRelativeCoordinates.js",
    "file"
  ],
  [
    "apps/templow/client/components/heatmap/index.js",
    "file/apps/tempLow/client/components/Heatmap/index.js.html",
    "apps/tempLow/client/components/Heatmap/index.js",
    "file"
  ],
  [
    "apps/templow/client/components/heatmap/index.js~heatmap#clearcoords",
    "class/apps/tempLow/client/components/Heatmap/index.js~Heatmap.html#instance-member-clearCoords",
    "apps/tempLow/client/components/Heatmap/index.js~Heatmap#clearCoords",
    "member"
  ],
  [
    "apps/templow/client/components/heatmap/index.js~heatmap#componentwillreceiveprops",
    "class/apps/tempLow/client/components/Heatmap/index.js~Heatmap.html#instance-method-componentWillReceiveProps",
    "apps/tempLow/client/components/Heatmap/index.js~Heatmap#componentWillReceiveProps",
    "method"
  ],
  [
    "apps/templow/client/components/heatmap/index.js~heatmap#constructor",
    "class/apps/tempLow/client/components/Heatmap/index.js~Heatmap.html#instance-constructor-constructor",
    "apps/tempLow/client/components/Heatmap/index.js~Heatmap#constructor",
    "method"
  ],
  [
    "apps/templow/client/components/heatmap/index.js~heatmap#container",
    "class/apps/tempLow/client/components/Heatmap/index.js~Heatmap.html#instance-member-container",
    "apps/tempLow/client/components/Heatmap/index.js~Heatmap#container",
    "member"
  ],
  [
    "apps/templow/client/components/heatmap/index.js~heatmap#handlemousemove",
    "class/apps/tempLow/client/components/Heatmap/index.js~Heatmap.html#instance-member-handleMouseMove",
    "apps/tempLow/client/components/Heatmap/index.js~Heatmap#handleMouseMove",
    "member"
  ],
  [
    "apps/templow/client/components/heatmap/index.js~heatmap#render",
    "class/apps/tempLow/client/components/Heatmap/index.js~Heatmap.html#instance-method-render",
    "apps/tempLow/client/components/Heatmap/index.js~Heatmap#render",
    "method"
  ],
  [
    "apps/templow/client/components/heatmap/index.js~heatmap#selectentry",
    "class/apps/tempLow/client/components/Heatmap/index.js~Heatmap.html#instance-member-selectEntry",
    "apps/tempLow/client/components/Heatmap/index.js~Heatmap#selectEntry",
    "member"
  ],
  [
    "apps/templow/client/components/heatmap/index.js~heatmap#state",
    "class/apps/tempLow/client/components/Heatmap/index.js~Heatmap.html#instance-member-state",
    "apps/tempLow/client/components/Heatmap/index.js~Heatmap#state",
    "member"
  ],
  [
    "apps/templow/client/components/heatmap/index.js~heatmap.defaultprops",
    "class/apps/tempLow/client/components/Heatmap/index.js~Heatmap.html#static-member-defaultProps",
    "apps/tempLow/client/components/Heatmap/index.js~Heatmap.defaultProps",
    "member"
  ],
  [
    "apps/templow/client/components/heatmap/index.js~heatmap.proptypes",
    "class/apps/tempLow/client/components/Heatmap/index.js~Heatmap.html#static-member-propTypes",
    "apps/tempLow/client/components/Heatmap/index.js~Heatmap.propTypes",
    "member"
  ],
  [
    "apps/templow/client/index.js",
    "file/apps/tempLow/client/index.js.html",
    "apps/tempLow/client/index.js",
    "file"
  ],
  [
    "apps/templow/server/index.js",
    "file/apps/tempLow/server/index.js.html",
    "apps/tempLow/server/index.js",
    "file"
  ],
  [
    "apps/templow/server/models/temperaturerecord.js",
    "file/apps/tempLow/server/models/TemperatureRecord.js.html",
    "apps/tempLow/server/models/TemperatureRecord.js",
    "file"
  ],
  [
    "apps/templow/server/preparedata.js",
    "file/apps/tempLow/server/prepareData.js.html",
    "apps/tempLow/server/prepareData.js",
    "file"
  ]
]